### ISSUE TITLE
Bug 0.22.3? Import fails.

### ISSUE THREAD

**Issue by kristofer** [martinpaljak/M2Crypto#60]
pip install m2crypto, install swig and pcre....
then do pip install M2Crypto again, and get 
```
...bunch of stuff, clip....
    SWIG/_m2crypto_wrap.c:21558:14: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
          arg4 = len;
               ~ ^~~
    SWIG/_m2crypto_wrap.c:24685:14: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
          arg3 = len;
               ~ ^~~
    19 warnings generated.
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.10-intel-2.7/SWIG/_m2crypto_wrap.o -L/usr/lib -lssl -lcrypto -o build/lib.macosx-10.10-intel-2.7/M2Crypto/__m2crypto.so
    
Successfully installed m2crypto
Cleaning up...
```
but then,
```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import M2Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/__init__.py", line 24, in <module>
    import ASN1
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 12, in <module>
    import BIO
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/BIO.py", line 221, in <module>
    class CipherStream(BIO):
  File "/Volumes/Kristofer/ExternalUsers/kyounger/Projects/tioga-flask-mini/venv/lib/python2.7/site-packages/M2Crypto/BIO.py", line 227, in CipherStream
    SALT_LEN = m2.PKCS5_SALT_LEN
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'
```

I am inside a virtualenv, keeping my depns to a minimum.

**Comment by danmcd** [comment]
Which version of SWIG did you use?  A different (older) M2Crypto repo has a report on it.  Apparently swig 3.0.5 breaks M2Crypto.  I hear swig 3.0.4 doesn't.  I'm trying it now myself.  You should see if using SWIG 3.0.4 works.

(So it's either a bug in SWIG 3.0.5 or in M2Crypto. SOMEONE should find out which.)

**Comment by DimStar77** [comment]
I tried to bisect swig and filed issue https://github.com/swig/swig/issues/344

**Comment by ptomulik** [comment]
I think this may be an "order of initialization" issue. I see, that your ``__init__.py`` imports stuff from it's own package. My experience shows, that this used to cause unpredictable results. The following commit: https://github.com/swig/swig/commit/06fb68af5b243787e31062e60356c739e56c06de changed the initialization order of constants in swig, such that they're initialized after a swig-generated type-system (this was necessary to handle object constants properly).

As a remedy, you may try ``-relativeimport`` swig flag, as described in the swig manual: http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_importfrominit

**Comment by DimStar77** [comment]
A first test to invoke swig using
> swig -python -I/usr/include/python2.7 -I/usr/include -I/usr/include/openssl -includeall -modern -relativeimport -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
did not lead to a working M2Crypto module

**Comment by ptomulik** [comment]
I've also spot few other code lines that looks strange, for example:

- https://github.com/martinpaljak/M2Crypto/blob/master/M2Crypto/m2.py#L28
- https://github.com/martinpaljak/M2Crypto/blob/master/M2Crypto/__init__.py#L22

You ignore the generated shadow file ``_m2crypto.py`` which originally lands in ``SWIG/`` directory (a python shadow file). I think, you should import ``_m2crypto`` instead of ``__m2crypto``, because it's the ``_m2crypto`` module which loads all the module constants.

**Comment by DimStar77** [comment]
:( seems there are a bunch of things 'wrong' that were masked away... 

I now attempted using the shadow file, changed the various import __m2crypto to _mcrypto, but this resolved in a not much nicer error:

<pre>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/M2Crypto/__init__.py", line 22, in <module>
    import _m2crypto
  File "/usr/lib64/python2.7/site-packages/M2Crypto/_m2crypto.py", line 117, in <module>
    class _STACK(object):
  File "/usr/lib64/python2.7/site-packages/M2Crypto/_m2crypto.py", line 120, in _STACK
    num = _swig_property(__m2crypto._STACK_num_get, __m2crypto._STACK_num_set)
NameError: name '_STACK__m2crypto' is not defined
</pre>

**Comment by ptomulik** [comment]
Yup, I've seen this. Trying to elaborate.

**Comment by ptomulik** [comment]
I've tried to generate interface using ``-builtin`` flag, but this leads to the following errors:
```
ypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-2.7/SWIG/_m2crypto_wrap.o -DTHREADING
SWIG/_m2crypto_wrap.c: In function ‘ssl_verify_callback’:
SWIG/_m2crypto_wrap.c:1147:83: error: ‘self’ undeclared (first use in this function)
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(self, ptr, type, flags)
                                                                                   ^
SWIG/_m2crypto_wrap.c:3737:35: note: in expansion of macro ‘SWIG_NewPointerObj’
         _x509_store_ctx_swigptr = SWIG_NewPointerObj((void *)ctx, SWIGTYPE_p_X509_STORE_CTX, 0);
                                   ^
SWIG/_m2crypto_wrap.c:1147:83: note: each undeclared identifier is reported only once for each function it appears in
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(self, ptr, type, flags)
                                                                                   ^
SWIG/_m2crypto_wrap.c:3737:35: note: in expansion of macro ‘SWIG_NewPointerObj’
         _x509_store_ctx_swigptr = SWIG_NewPointerObj((void *)ctx, SWIGTYPE_p_X509_STORE_CTX, 0);
                                   ^
SWIG/_m2crypto_wrap.c: In function ‘ssl_info_callback’:
SWIG/_m2crypto_wrap.c:1147:83: error: ‘self’ undeclared (first use in this function)
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(self, ptr, type, flags)
                                                                                   ^
SWIG/_m2crypto_wrap.c:3795:12: note: in expansion of macro ‘SWIG_NewPointerObj’
     _SSL = SWIG_NewPointerObj((void *)s, SWIGTYPE_p_SSL, 0);
            ^
SWIG/_m2crypto_wrap.c: In function ‘ssl_set_tmp_dh_callback’:
SWIG/_m2crypto_wrap.c:1147:83: error: ‘self’ undeclared (first use in this function)
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(self, ptr, type, flags)
                                                                                   ^
SWIG/_m2crypto_wrap.c:3814:12: note: in expansion of macro ‘SWIG_NewPointerObj’
     _ssl = SWIG_NewPointerObj((void *)ssl, SWIGTYPE_p_SSL, 0);
            ^
SWIG/_m2crypto_wrap.c: In function ‘ssl_set_tmp_rsa_callback’:
SWIG/_m2crypto_wrap.c:1147:83: error: ‘self’ undeclared (first use in this function)
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(self, ptr, type, flags)
                                                                                   ^
SWIG/_m2crypto_wrap.c:3837:12: note: in expansion of macro ‘SWIG_NewPointerObj’
     _ssl = SWIG_NewPointerObj((void *)ssl, SWIGTYPE_p_SSL, 0);
            ^
SWIG/_m2crypto_wrap.c: At top level:
SWIG/_m2crypto_wrap.c:3898:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void lib_init() {
      ^
SWIG/_m2crypto_wrap.c: In function ‘x509v3_lhash’:
SWIG/_m2crypto_wrap.c:6879:5: warning: return from incompatible pointer type
     return lh_new(NULL, NULL); /* Should probably be lh_CONF_VALUE_new but won't compile. */
     ^
SWIG/_m2crypto_wrap.c: In function ‘smime_read_pkcs7’:
SWIG/_m2crypto_wrap.c:1147:83: error: ‘self’ undeclared (first use in this function)
 #define SWIG_NewPointerObj(ptr, type, flags)            SWIG_Python_NewPointerObj(self, ptr, type, flags)
                                                                                   ^
SWIG/_m2crypto_wrap.c:7260:11: note: in expansion of macro ‘SWIG_NewPointerObj’
     _p7 = SWIG_NewPointerObj((void *)p7, SWIGTYPE_p_PKCS7, 0);
           ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Some errors originate from functions defined in SWIG/_lib.i

**Comment by ptomulik** [comment]
Ok, I've managed to make few hacks such that the ``M2Crypto`` module imports. Below is a patch. What's left is to ensure, that ``SWIG/_m2crypto.py`` gets installed in an appropriate place. You should check whether it works proprerly, as I was concerned on the import issue only.

```
diff --git a/M2Crypto/__init__.py b/M2Crypto/__init__.py
index 647e057..62a9fb5 100644
--- a/M2Crypto/__init__.py
+++ b/M2Crypto/__init__.py
@@ -19,7 +19,7 @@ Copyright 2008-2011 Heikki Toivonen. All rights reserved.
 version_info = (0, 22)
 version = '.'.join([str(_v) for _v in version_info])
 
-import __m2crypto
+import _m2crypto
 import m2
 import ASN1
 import AuthCookie
diff --git a/M2Crypto/m2.py b/M2Crypto/m2.py
index e4bb695..822143f 100644
--- a/M2Crypto/m2.py
+++ b/M2Crypto/m2.py
@@ -25,7 +25,7 @@ Portions created by Open Source Applications Foundation (OSAF) are
 Copyright (C) 2004 OSAF. All Rights Reserved.
 """
 
-from __m2crypto import *
+from _m2crypto import *
 lib_init()
 
 
diff --git a/SWIG/_lib.i b/SWIG/_lib.i
index 0d40698..c74e531 100644
--- a/SWIG/_lib.i
+++ b/SWIG/_lib.i
@@ -66,6 +66,8 @@ int ssl_verify_callback(int ok, X509_STORE_CTX *ctx) {
     int cret;
     int new_style_callback = 0, warning_raised_exception=0;
     PyGILState_STATE gilstate;
+    PyObject *self = 0;
+    (void)self;
 
     ssl = (SSL *)X509_STORE_CTX_get_app_data(ctx);
 
@@ -151,6 +153,8 @@ int ssl_verify_callback(int ok, X509_STORE_CTX *ctx) {
 void ssl_info_callback(const SSL *s, int where, int ret) {
     PyObject *argv, *retval, *_SSL;
     PyGILState_STATE gilstate;
+    PyObject *self = 0;
+    (void)self;
 
     gilstate = PyGILState_Ensure();
 
@@ -170,6 +174,8 @@ DH *ssl_set_tmp_dh_callback(SSL *ssl, int is_export, int keylength) {
     PyObject *argv, *ret, *_ssl;
     DH *dh;
     PyGILState_STATE gilstate;
+    PyObject *self = 0;
+    (void)self;
 
     gilstate = PyGILState_Ensure();
 
@@ -193,6 +199,8 @@ RSA *ssl_set_tmp_rsa_callback(SSL *ssl, int is_export, int keylength) {
     PyObject *argv, *ret, *_ssl;
     RSA *rsa;
     PyGILState_STATE gilstate;
+    PyObject *self = 0;
+    (void)self;
 
     gilstate = PyGILState_Ensure();
 
diff --git a/SWIG/_pkcs7.i b/SWIG/_pkcs7.i
index 22d791a..92b1aeb 100644
--- a/SWIG/_pkcs7.i
+++ b/SWIG/_pkcs7.i
@@ -157,6 +157,8 @@ PyObject *smime_read_pkcs7(BIO *bio) {
     BIO *bcont = NULL;
     PKCS7 *p7;
     PyObject *tuple, *_p7, *_BIO;
+    PyObject *self = 0;
+    (void)self;
 
     if (BIO_method_type(bio) == BIO_TYPE_MEM) {
         /* OpenSSL FAQ explains that this is needed for mem BIO to return EOF,
diff --git a/setup.py b/setup.py
index 0bdcbd0..8da24e3 100644
--- a/setup.py
+++ b/setup.py
@@ -76,7 +76,9 @@ class _M2CryptoBuildExt(build_ext.build_ext):
         self.swig_opts = ['-I%s' % i for i in self.include_dirs + \
                           [opensslIncludeDir, os.path.join(opensslIncludeDir, "openssl")]]
         self.swig_opts.append('-includeall')
-        self.swig_opts.append('-modern')
+        ##self.swig_opts.append('-modern')
+        self.swig_opts.append('-builtin')
+        self.swig_opts.append('-relativeimport')
 
         # Fedora does hat tricks.
         if os.path.isfile('/etc/redhat-release'):
```

**Comment by DimStar77** [comment]
@ptomulik Thanks a lot! I added your patch to my local packages and this does indeed seem to work; the first tests with the resulting package were also good (but it was very limited testing).

**Comment by ptomulik** [comment]
You probably could remove the ``-relativeimport``. If your package imports properly withouth this flag, then it's better to not use it (relateive imports are deprecated in python, and are absent in python >= 3.x, this flag is mainly for backward compatibility).

**Comment by DimStar77** [comment]
I tried without -relativimport: this works; what IS mandatory is the use of -builtin.

**Comment by DimStar77** [comment]
-builtin -modern is also a working combination.

**Comment by masterkorp** [comment]
Hello @DimStar77 

Are there any updates on this issue ? Has the fix been merged to master ?

**Comment by joejulian** [comment]
https://github.com/M2Crypto/M2Crypto/pull/30 needs to be further tested if anybody else wants to try.

**Comment by Kendos-Kenlen** [comment]
Is problem solved ? It create problem during the compilation of CRDA on Exherbo (Linux).

**Comment by joejulian** [comment]
Last commit was May 6, 2014. I think it's dead.

**Comment by mcepl** [comment]
It is not dead. It is pinning for the fjords. I will do something around this weekend.

**Comment by mcepl** [comment]
See https://github.com/mcepl/M2Crypto/issues/5#issuecomment-143864616

**Comment by mcepl** [comment]
New version 0.22.4 has been released on PyPI, which fixes this issue, and the new upstream for this project is now officially https://gitlab.com/m2crypto/m2crypto/ Please, file all issues, merge requests, etc. there.

This ticket can be closed now.

**Comment by mcepl** [comment]
Would anybody here be able to help with https://gitlab.com/m2crypto/m2crypto/issues/49?
